### ISSUE TITLE
Support /me and/or asterisks for character actions

### ISSUE THREAD

**Issue by Lana-chan** [shamblesides/rpnow#1]
Currently, the only way to write a character action is through the Narrator character.

**Comment by frostyfrog** [comment]
Looking at this, it made me wonder if there should be a /ooc option as well.

**Comment by Lana-chan** [comment]
In the same vein that actions can be represented as *does thing*, one 
way I personally prefer to type OOC is using (( parentheses like these 
)). /ooc could be complimentary to /me.

**Comment by shamblesides** [comment]
This is late, but OOC and asterisks are both implemented now!
